# Generated by Django 2.2.6 on 2019-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
